<<<<<<< HEAD
=======
"use client";
>>>>>>> d1c1083bc17743dfa3e65967429a7359ee273a3b
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
 
=======
  const logeo = async () => {
    const _credencial: Credentials = {
      Username: `${process.env.NEXT_PUBLIC_API_USERNAME}`,
      Password: `${process.env.NEXT_PUBLIC_API_PASSWORD}`,
    };

    const response = await Login(_credencial);
    if (response.statusCode === 200) {
      setCookie("Token", response.value);
    }
  };

  useEffect(() => {
    if (typeof window !== "undefined") {
      if (!token) {
        // Redirigir a la página de inicio de sesión
        logeo();
      }
    }
  }, []);

>>>>>>> d1c1083bc17743dfa3e65967429a7359ee273a3b
  return (
    <html lang="en">
      <Menu />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <Footer />
    </html>
  );
}
